import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";
import Layout from "@/components/layout";
import Footer from "@/components/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Engineering Fjordstans",
  description: "Generated by create next app",
  icons: {
    icon: "/logo/logo-single.png",
    apple: "/logo/logo-single.png",
  }
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Layout>
          <Navbar />
          {children}
          <Footer />
        </Layout>
      </body>
    </html>
  );
}
